# Generated by Django 5.2 on 2025-04-27 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_missing_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
